[package]
name = "ask_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0.32", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
reqwest = { version = "0.11", features = ["blocking", "json", "rustls-tls"] }
whoami = "1.3"
colored = "2.0"
base64 = "0.13"
term_size = "0.3"
